name: Deploy React App to AWS S3


on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  S3_BUCKET: dipti-aws-react-demo


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: '18'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Important

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with: 
          name: 'aws-react-app'
          path: ./build
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3
      id: deployment
      run: |
        aws s3 sync ./build/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
